In [1]:
import numpy as np
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c)

[[ 0.69341163  0.11289821  1.18254457]
 [ 0.0273504  -0.00900781 -0.01570518]
 [ 0.47947104  0.08721922 -0.74955742]]


In [3]:
a=np.array([[2,1],[1,3]])
print((a*a))
c=np.dot(a,a)
print(c)

[[4 1]
 [1 9]]
[[ 5  5]
 [ 5 10]]


In [4]:
a=np.array([[1,1],[1,-1]])
b=np.array([[2],[3]])
c=a+b
print(c)

[[3 3]
 [4 2]]


In [5]:
a=np.random.randn(12288,150) 
#a.shape=(12288,150)
b=np.random.randn(150,45) 
#b.shape=(150,45)
c=np.dot(a,b) 
print(c.shape)

(12288, 45)


In [15]:
x=np.zeros((5,1),dtype='float32')
x

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [2]:
x = np.random.rand(4, 5)

y = np.sum(x, axis=1)

In [3]:
y.shape

(4,)

In [4]:
x = np.random.rand(3, 2)
y = np.sum(x, axis=0, keepdims=True)
y.shape

(1, 2)